version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=movieDB
      - MYSQL_ROOT_PASSWORD=bjit1234
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./movies.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
